"""第3段階: ポートフォリオの初期分類情報・追加ポートフォリオのシードデータ。

第2段階で登録済みの7件の制作実績には URL・カテゴリ分類が未設定だったため、
ここで「空欄の項目のみ」を補完する（ユーザーが既に編集した値は上書きしない）。
また、AI・開発ポートフォリオ／デザインポートフォリオ／GitHubの3件は
第2段階では未登録だったため、新規に追加する。

登録URLが不明な実績にはURLを設定せず、虚偽のURLを作成しない。
"""
from __future__ import annotations

# 既存7件の制作実績（タイトルで一致させる）を補完する情報。
# 値が空の列にのみ適用し、既に値が入っている列は上書きしない。
EXISTING_PORTFOLIO_ENRICHMENT: dict[str, dict] = {
    "Googleマップ×ホームページ生成システム": {
        "portfolio_url": "https://curious-concha-3d7f92.netlify.app/",
        "portfolio_type": "development",
        "main_category": "AI・Web制作・業務自動化",
        "subcategories": ["Web制作", "業務自動化"],
        "target_job_categories": ["ホームページ制作案件", "業務自動化案件"],
        "technology_keywords": ["Google Maps API", "ホームページ制作", "店舗情報", "Webサイト生成", "業務効率化"],
        "design_tools": [],
        "sales_description": "Googleマップの店舗情報をもとにホームページのたたき台を自動生成するシステムを開発した経験があります。",
        "priority": 50,
        "for_development": True,
        "for_design": False,
        "for_ai_design": False,
        "display_order": 10,
    },
    "歌舞伎予習AIチャットボット": {
        "github_url": "https://github.com/moedaichi0629-ai/kabuki-chatbot",
        "portfolio_type": "development",
        "main_category": "AIチャットボット",
        "subcategories": ["AIチャットボット"],
        "target_job_categories": ["AIチャットボット開発案件", "API連携案件"],
        "technology_keywords": ["Dify", "React", "AIチャットボット", "API連携", "情報整理"],
        "design_tools": [],
        "sales_description": "Difyを用いたAIチャットボットを個人開発した経験があります。",
        "priority": 50,
        "for_development": True,
        "for_design": False,
        "for_ai_design": False,
        "display_order": 11,
    },
    "AI ToDoリスト": {
        "portfolio_type": "development",
        "main_category": "AI Webアプリ",
        "subcategories": ["タスク管理"],
        "target_job_categories": ["Webアプリ開発案件"],
        "technology_keywords": ["React", "Google Sheets", "AIタスク分解", "ダッシュボード", "タスク管理"],
        "design_tools": [],
        "sales_description": "AIによるタスク分解機能を備えたタスク管理Webアプリを個人開発した経験があります。",
        "priority": 40,
        "for_development": True,
        "for_design": False,
        "for_ai_design": False,
        "display_order": 12,
    },
    "AI文章添削ツール": {
        "portfolio_type": "development",
        "main_category": "AI文章生成",
        "subcategories": ["文章添削"],
        "target_job_categories": ["AI文章生成案件", "AI活用案件"],
        "technology_keywords": ["Python", "Streamlit", "OpenAI API", "文章添削", "プロンプト設計"],
        "design_tools": [],
        "sales_description": "OpenAI APIを利用した文章添削ツールを個人開発した経験があります。",
        "priority": 40,
        "for_development": True,
        "for_design": False,
        "for_ai_design": False,
        "display_order": 13,
    },
    "AI日程調整ツール": {
        "portfolio_type": "development",
        "main_category": "業務自動化",
        "subcategories": ["日程調整"],
        "target_job_categories": ["業務自動化案件", "API連携案件"],
        "technology_keywords": ["Google Calendar API", "OAuth", "Streamlit", "日程調整", "自動化"],
        "design_tools": [],
        "sales_description": "Googleカレンダー連携による日程調整ツールを個人開発した経験があります。",
        "priority": 40,
        "for_development": True,
        "for_design": False,
        "for_ai_design": False,
        "display_order": 14,
    },
    "天気予報Webアプリ": {
        "portfolio_type": "development",
        "main_category": "Webアプリ",
        "subcategories": ["データ可視化"],
        "target_job_categories": ["Webアプリ開発案件"],
        "technology_keywords": ["React", "OpenWeather API", "データ可視化", "API連携", "レスポンシブ"],
        "design_tools": [],
        "sales_description": "外部APIと連携したレスポンシブな天気予報Webアプリを個人開発した経験があります。",
        "priority": 30,
        "for_development": True,
        "for_design": False,
        "for_ai_design": False,
        "display_order": 15,
    },
    "LINE連携ライブ思い出アルバム": {
        "portfolio_type": "development",
        "main_category": "LINE・Google連携",
        "subcategories": ["自動生成"],
        "target_job_categories": ["LINE連携案件", "業務自動化案件"],
        "technology_keywords": ["LINE Messaging API", "Google Docs", "Google Drive", "Google Sheets", "自動生成"],
        "design_tools": [],
        "sales_description": "LINE Messaging APIとGoogle連携による自動アルバム生成システムを個人開発した経験があります。",
        "priority": 40,
        "for_development": True,
        "for_design": False,
        "for_ai_design": False,
        "display_order": 16,
    },
}

# 新規に登録する3件（AI・開発の総合ポートフォリオ／デザインポートフォリオ／GitHub）。
NEW_DEFAULT_PORTFOLIOS: list[dict] = [
    {
        "title": "AIエンジニア・Web制作ポートフォリオ",
        "description": "AI開発・Webアプリ・API連携・業務自動化・ホームページ制作をまとめた総合ポートフォリオ。",
        "technologies": ["AI", "Python", "React", "Streamlit", "API", "Webアプリ", "自動化", "ホームページ制作"],
        "skills": ["AI開発", "Webアプリ", "API連携", "業務自動化", "ホームページ制作"],
        "portfolio_url": "https://moedaichi0629-ai.github.io/landing-page/",
        "github_url": None,
        "portfolio_type": "development",
        "main_category": "AI・Web開発・総合ポートフォリオ",
        "subcategories": ["AI開発", "Webアプリ", "API連携", "業務自動化", "ホームページ制作"],
        "target_job_categories": ["AI関連案件", "Web開発案件", "API連携案件", "業務自動化案件", "ホームページ制作案件"],
        "design_tools": [],
        "technology_keywords": ["AI", "Python", "React", "Streamlit", "API", "Webアプリ", "自動化", "ホームページ制作"],
        "sales_description": "AI開発・Webアプリ・API連携・業務自動化まで幅広く対応できることをまとめたポートフォリオです。",
        "priority": 100,
        "for_development": True,
        "for_design": False,
        "for_ai_design": True,
        "display_order": 0,
    },
    {
        "title": "グラフィック・Webデザイン ポートフォリオ",
        "description": "バナー・SNS投稿画像・YouTubeサムネイル・ロゴ・名刺・チラシ・Webデザイン等の制作実績（foriio）。",
        "technologies": [],
        "skills": [
            "Illustrator", "Photoshop", "バナー", "SNS投稿画像", "YouTubeサムネイル", "ロゴ", "名刺",
            "ショップカード", "チラシ", "販促物", "Webデザイン", "LPデザイン", "グラフィックデザイン",
        ],
        "portfolio_url": "https://www.foriio.com/rilymoe0902",
        "github_url": None,
        "portfolio_type": "design",
        "main_category": "デザイン制作実績",
        "subcategories": [
            "グラフィックデザイン", "Webデザイン", "バナーデザイン", "SNSデザイン", "YouTubeサムネイル",
            "ロゴ", "名刺", "チラシ", "印刷物",
        ],
        "target_job_categories": [
            "バナー制作案件", "SNS投稿画像制作案件", "YouTubeサムネイル制作案件", "ロゴ制作案件",
            "名刺・ショップカード制作案件", "チラシ・販促物制作案件", "Webデザイン案件", "LPデザイン案件", "資料デザイン案件",
        ],
        "design_tools": ["Illustrator", "Photoshop"],
        "technology_keywords": [
            "Illustrator", "Photoshop", "バナー", "SNS投稿画像", "YouTubeサムネイル", "ロゴ", "名刺",
            "ショップカード", "チラシ", "販促物", "Webデザイン", "LPデザイン", "グラフィックデザイン",
        ],
        "sales_description": "Illustrator・Photoshopを使用したバナー、SNS投稿画像、ロゴ、Webデザインなどの制作実績です。",
        "priority": 100,
        "for_development": False,
        "for_design": True,
        "for_ai_design": True,
        "display_order": 1,
    },
    {
        "title": "GitHub",
        "description": "ソースコード・開発履歴を公開しているGitHubアカウント。",
        "technologies": [],
        "skills": [],
        "portfolio_url": None,
        "github_url": "https://github.com/moedaichi0629-ai",
        "portfolio_type": "development",
        "main_category": "ソースコード・開発実績",
        "subcategories": [],
        "target_job_categories": ["AI案件", "API連携案件", "Webアプリ開発案件", "技術力の確認が必要な案件"],
        "design_tools": [],
        "technology_keywords": [],
        "sales_description": "GitHubで実際のソースコードや開発履歴を確認いただけます。",
        "priority": 60,
        "for_development": True,
        "for_design": False,
        "for_ai_design": False,
        "display_order": 2,
    },
]
